name: 'Setup Build Environment'
runs:
  using: "composite"
  steps:
    - name: Install prerequisite packages
      shell: bash
      run: |
        curl -O https://practicerom.com/public/packages/debian/dists/stable/practicerom-repository_latest_$(dpkg --print-architecture).deb
        sudo dpkg -i practicerom-repository_latest_$(dpkg --print-architecture).deb
        sudo apt-get update
        sudo apt-get install -y practicerom-dev xdelta3 ninja-build
        pip install --break-system-packages -r requirements.txt