name: Build fp patches

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisite packages
      run: |
        curl https://practicerom.com/public/packages/debian/pgp.pub | sudo apt-key add -
        echo deb https://practicerom.com/public/packages/debian ./staging main | sudo tee /etc/apt/sources.list.d/practicerom.list
        sudo apt-get update
        sudo apt-get install practicerom-dev xdelta3
    - name: Download ROMs
      run: |
        mkdir rom
        curl -sL -o base-jp.z64 ${{ secrets.JP_ROM }}
        curl -sL -o base-us.z64 ${{ secrets.US_ROM }}
    - name: Make fp ROMs
      run: |
        ./makerom base-jp.z64
        ./makerom base-us.z64
    - name: Create xdelta patches
      run: |
        xdelta3 -e -S none -s base-jp.z64 fp-jp.z64 fp-jp.xdelta
        xdelta3 -e -S none -s base-us.z64 fp-us.z64 fp-us.xdelta
    - name: Upload JP patch
      uses: actions/upload-artifact@v2.2.4
      with:
        name: fp-jp.xdelta
        path: fp-jp.xdelta
    - name: Upload US patch
      uses: actions/upload-artifact@v2.2.4
      with:
        name: fp-us.xdelta
        path: fp-us.xdelta
